name: Preview

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add private overrides for releases
        env:
          PRIVATE_CONTENT: ${{ secrets.PRIVATE_CONTENT }}
        run: |
          echo $PRIVATE_CONTENT > RohitGohri.tmp
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Generate PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            resume.tex
          args: |
            -pdf -interaction=nonstopmode -file-line-error -halt-on-error -jobname=RohitGohri

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v1
        with:
          name: resume-preview
          path: RohitGohri.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: resume-preview

      - name: Upload Pre-Release
        uses: eine/tip@master
        with:
          tag: next
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            RohitGohri.pdf

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: RohitGohri.pdf
          draft: false
          prerelease: false
        if: startsWith(github.ref, 'refs/tags/v')
